// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetPendingContributions_FullMethodName = "/admin.AdminService/GetPendingContributions"
	AdminService_ApproveContribution_FullMethodName     = "/admin.AdminService/ApproveContribution"
	AdminService_GetContributionStats_FullMethodName    = "/admin.AdminService/GetContributionStats"
	AdminService_GetDashboardOverview_FullMethodName    = "/admin.AdminService/GetDashboardOverview"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Admin Service - handles admin operations and approval workflows
type AdminServiceClient interface {
	// Get pending contributions for admin review
	GetPendingContributions(ctx context.Context, in *GetPendingContributionsRequest, opts ...grpc.CallOption) (*GetPendingContributionsResponse, error)
	// Approve or reject a contribution
	ApproveContribution(ctx context.Context, in *ApproveContributionRequest, opts ...grpc.CallOption) (*ApproveContributionResponse, error)
	// Get contribution statistics for admin dashboard
	GetContributionStats(ctx context.Context, in *GetContributionStatsRequest, opts ...grpc.CallOption) (*GetContributionStatsResponse, error)
	// Get admin dashboard overview
	GetDashboardOverview(ctx context.Context, in *GetDashboardOverviewRequest, opts ...grpc.CallOption) (*GetDashboardOverviewResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetPendingContributions(ctx context.Context, in *GetPendingContributionsRequest, opts ...grpc.CallOption) (*GetPendingContributionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingContributionsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetPendingContributions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApproveContribution(ctx context.Context, in *ApproveContributionRequest, opts ...grpc.CallOption) (*ApproveContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveContributionResponse)
	err := c.cc.Invoke(ctx, AdminService_ApproveContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetContributionStats(ctx context.Context, in *GetContributionStatsRequest, opts ...grpc.CallOption) (*GetContributionStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContributionStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetContributionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDashboardOverview(ctx context.Context, in *GetDashboardOverviewRequest, opts ...grpc.CallOption) (*GetDashboardOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardOverviewResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDashboardOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// Admin Service - handles admin operations and approval workflows
type AdminServiceServer interface {
	// Get pending contributions for admin review
	GetPendingContributions(context.Context, *GetPendingContributionsRequest) (*GetPendingContributionsResponse, error)
	// Approve or reject a contribution
	ApproveContribution(context.Context, *ApproveContributionRequest) (*ApproveContributionResponse, error)
	// Get contribution statistics for admin dashboard
	GetContributionStats(context.Context, *GetContributionStatsRequest) (*GetContributionStatsResponse, error)
	// Get admin dashboard overview
	GetDashboardOverview(context.Context, *GetDashboardOverviewRequest) (*GetDashboardOverviewResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetPendingContributions(context.Context, *GetPendingContributionsRequest) (*GetPendingContributionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingContributions not implemented")
}
func (UnimplementedAdminServiceServer) ApproveContribution(context.Context, *ApproveContributionRequest) (*ApproveContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveContribution not implemented")
}
func (UnimplementedAdminServiceServer) GetContributionStats(context.Context, *GetContributionStatsRequest) (*GetContributionStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContributionStats not implemented")
}
func (UnimplementedAdminServiceServer) GetDashboardOverview(context.Context, *GetDashboardOverviewRequest) (*GetDashboardOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardOverview not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetPendingContributions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingContributionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPendingContributions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPendingContributions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPendingContributions(ctx, req.(*GetPendingContributionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApproveContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApproveContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApproveContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApproveContribution(ctx, req.(*ApproveContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetContributionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContributionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetContributionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetContributionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetContributionStats(ctx, req.(*GetContributionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDashboardOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDashboardOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDashboardOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDashboardOverview(ctx, req.(*GetDashboardOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingContributions",
			Handler:    _AdminService_GetPendingContributions_Handler,
		},
		{
			MethodName: "ApproveContribution",
			Handler:    _AdminService_ApproveContribution_Handler,
		},
		{
			MethodName: "GetContributionStats",
			Handler:    _AdminService_GetContributionStats_Handler,
		},
		{
			MethodName: "GetDashboardOverview",
			Handler:    _AdminService_GetDashboardOverview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin.proto",
}
