// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for getting pending contributions
type GetPendingContributionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int32                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FilterType    string                 `protobuf:"bytes,3,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"` // "all", "new", "update", "correction"
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`             // "created_at", "user_id", "digimon_id"
	SortOrder     string                 `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`    // "asc", "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingContributionsRequest) Reset() {
	*x = GetPendingContributionsRequest{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingContributionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingContributionsRequest) ProtoMessage() {}

func (x *GetPendingContributionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingContributionsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingContributionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetPendingContributionsRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetPendingContributionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPendingContributionsRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *GetPendingContributionsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetPendingContributionsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// Response for pending contributions
type GetPendingContributionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contributions []*PendingContribution `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingContributionsResponse) Reset() {
	*x = GetPendingContributionsResponse{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingContributionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingContributionsResponse) ProtoMessage() {}

func (x *GetPendingContributionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingContributionsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingContributionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetPendingContributionsResponse) GetContributions() []*PendingContribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

func (x *GetPendingContributionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request for approving a contribution
type ApproveContributionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContributionId string                 `protobuf:"bytes,1,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	AdminId        string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Decision       string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"` // "approve", "reject"
	Comments       string                 `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApproveContributionRequest) Reset() {
	*x = ApproveContributionRequest{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveContributionRequest) ProtoMessage() {}

func (x *ApproveContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveContributionRequest.ProtoReflect.Descriptor instead.
func (*ApproveContributionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveContributionRequest) GetContributionId() string {
	if x != nil {
		return x.ContributionId
	}
	return ""
}

func (x *ApproveContributionRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *ApproveContributionRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ApproveContributionRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *ApproveContributionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response for approving a contribution
type ApproveContributionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedContribution *ContributionStatus    `protobuf:"bytes,3,opt,name=updated_contribution,json=updatedContribution,proto3" json:"updated_contribution,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApproveContributionResponse) Reset() {
	*x = ApproveContributionResponse{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveContributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveContributionResponse) ProtoMessage() {}

func (x *ApproveContributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveContributionResponse.ProtoReflect.Descriptor instead.
func (*ApproveContributionResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveContributionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveContributionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApproveContributionResponse) GetUpdatedContribution() *ContributionStatus {
	if x != nil {
		return x.UpdatedContribution
	}
	return nil
}

// Request for getting contribution statistics
type GetContributionStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimePeriod    string                 `protobuf:"bytes,1,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"` // "day", "week", "month", "year"
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContributionStatsRequest) Reset() {
	*x = GetContributionStatsRequest{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContributionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContributionStatsRequest) ProtoMessage() {}

func (x *GetContributionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContributionStatsRequest.ProtoReflect.Descriptor instead.
func (*GetContributionStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetContributionStatsRequest) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

func (x *GetContributionStatsRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

// Response for contribution statistics
type GetContributionStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ContributionStats     `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContributionStatsResponse) Reset() {
	*x = GetContributionStatsResponse{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContributionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContributionStatsResponse) ProtoMessage() {}

func (x *GetContributionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContributionStatsResponse.ProtoReflect.Descriptor instead.
func (*GetContributionStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetContributionStatsResponse) GetStats() *ContributionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Request for getting dashboard overview
type GetDashboardOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardOverviewRequest) Reset() {
	*x = GetDashboardOverviewRequest{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardOverviewRequest) ProtoMessage() {}

func (x *GetDashboardOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardOverviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetDashboardOverviewRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

// Response for dashboard overview
type GetDashboardOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overview      *DashboardOverview     `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardOverviewResponse) Reset() {
	*x = GetDashboardOverviewResponse{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardOverviewResponse) ProtoMessage() {}

func (x *GetDashboardOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardOverviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetDashboardOverviewResponse) GetOverview() *DashboardOverview {
	if x != nil {
		return x.Overview
	}
	return nil
}

// Pending contribution with user information
type PendingContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DigimonId     string                 `protobuf:"bytes,3,opt,name=digimon_id,json=digimonId,proto3" json:"digimon_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,8,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	DigimonInfo   *DigimonInfo           `protobuf:"bytes,9,opt,name=digimon_info,json=digimonInfo,proto3" json:"digimon_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingContribution) Reset() {
	*x = PendingContribution{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingContribution) ProtoMessage() {}

func (x *PendingContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingContribution.ProtoReflect.Descriptor instead.
func (*PendingContribution) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *PendingContribution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PendingContribution) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PendingContribution) GetDigimonId() string {
	if x != nil {
		return x.DigimonId
	}
	return ""
}

func (x *PendingContribution) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PendingContribution) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PendingContribution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PendingContribution) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PendingContribution) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *PendingContribution) GetDigimonInfo() *DigimonInfo {
	if x != nil {
		return x.DigimonInfo
	}
	return nil
}

// User information for admin view
type UserInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username              string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar                string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	TotalContributions    int32                  `protobuf:"varint,5,opt,name=total_contributions,json=totalContributions,proto3" json:"total_contributions,omitempty"`
	ApprovedContributions int32                  `protobuf:"varint,6,opt,name=approved_contributions,json=approvedContributions,proto3" json:"approved_contributions,omitempty"`
	MemberSince           string                 `protobuf:"bytes,7,opt,name=member_since,json=memberSince,proto3" json:"member_since,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetTotalContributions() int32 {
	if x != nil {
		return x.TotalContributions
	}
	return 0
}

func (x *UserInfo) GetApprovedContributions() int32 {
	if x != nil {
		return x.ApprovedContributions
	}
	return 0
}

func (x *UserInfo) GetMemberSince() string {
	if x != nil {
		return x.MemberSince
	}
	return ""
}

// Digimon information for admin view
type DigimonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigimonInfo) Reset() {
	*x = DigimonInfo{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonInfo) ProtoMessage() {}

func (x *DigimonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonInfo.ProtoReflect.Descriptor instead.
func (*DigimonInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *DigimonInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DigimonInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DigimonInfo) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DigimonInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DigimonInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// Contribution status after approval/rejection
type ContributionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,3,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt    string                 `protobuf:"bytes,4,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	Comments      string                 `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionStatus) Reset() {
	*x = ContributionStatus{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionStatus) ProtoMessage() {}

func (x *ContributionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionStatus.ProtoReflect.Descriptor instead.
func (*ContributionStatus) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ContributionStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContributionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContributionStatus) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *ContributionStatus) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *ContributionStatus) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

// Contribution statistics
type ContributionStats struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	TotalPending          int32                     `protobuf:"varint,1,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`
	TotalApproved         int32                     `protobuf:"varint,2,opt,name=total_approved,json=totalApproved,proto3" json:"total_approved,omitempty"`
	TotalRejected         int32                     `protobuf:"varint,3,opt,name=total_rejected,json=totalRejected,proto3" json:"total_rejected,omitempty"`
	NewContributionsToday int32                     `protobuf:"varint,4,opt,name=new_contributions_today,json=newContributionsToday,proto3" json:"new_contributions_today,omitempty"`
	ApprovedToday         int32                     `protobuf:"varint,5,opt,name=approved_today,json=approvedToday,proto3" json:"approved_today,omitempty"`
	RejectedToday         int32                     `protobuf:"varint,6,opt,name=rejected_today,json=rejectedToday,proto3" json:"rejected_today,omitempty"`
	ByType                []*ContributionTypeStats  `protobuf:"bytes,7,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty"`
	ByStage               []*ContributionStageStats `protobuf:"bytes,8,rep,name=by_stage,json=byStage,proto3" json:"by_stage,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ContributionStats) Reset() {
	*x = ContributionStats{}
	mi := &file_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionStats) ProtoMessage() {}

func (x *ContributionStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionStats.ProtoReflect.Descriptor instead.
func (*ContributionStats) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ContributionStats) GetTotalPending() int32 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

func (x *ContributionStats) GetTotalApproved() int32 {
	if x != nil {
		return x.TotalApproved
	}
	return 0
}

func (x *ContributionStats) GetTotalRejected() int32 {
	if x != nil {
		return x.TotalRejected
	}
	return 0
}

func (x *ContributionStats) GetNewContributionsToday() int32 {
	if x != nil {
		return x.NewContributionsToday
	}
	return 0
}

func (x *ContributionStats) GetApprovedToday() int32 {
	if x != nil {
		return x.ApprovedToday
	}
	return 0
}

func (x *ContributionStats) GetRejectedToday() int32 {
	if x != nil {
		return x.RejectedToday
	}
	return 0
}

func (x *ContributionStats) GetByType() []*ContributionTypeStats {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *ContributionStats) GetByStage() []*ContributionStageStats {
	if x != nil {
		return x.ByStage
	}
	return nil
}

// Statistics by contribution type
type ContributionTypeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Pending       int32                  `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	Approved      int32                  `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	Rejected      int32                  `protobuf:"varint,5,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionTypeStats) Reset() {
	*x = ContributionTypeStats{}
	mi := &file_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionTypeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionTypeStats) ProtoMessage() {}

func (x *ContributionTypeStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionTypeStats.ProtoReflect.Descriptor instead.
func (*ContributionTypeStats) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ContributionTypeStats) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContributionTypeStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContributionTypeStats) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *ContributionTypeStats) GetApproved() int32 {
	if x != nil {
		return x.Approved
	}
	return 0
}

func (x *ContributionTypeStats) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

// Statistics by Digimon stage
type ContributionStageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Pending       int32                  `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	Approved      int32                  `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	Rejected      int32                  `protobuf:"varint,5,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContributionStageStats) Reset() {
	*x = ContributionStageStats{}
	mi := &file_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionStageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionStageStats) ProtoMessage() {}

func (x *ContributionStageStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionStageStats.ProtoReflect.Descriptor instead.
func (*ContributionStageStats) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ContributionStageStats) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ContributionStageStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContributionStageStats) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *ContributionStageStats) GetApproved() int32 {
	if x != nil {
		return x.Approved
	}
	return 0
}

func (x *ContributionStageStats) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

// Dashboard overview
type DashboardOverview struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Stats            *ContributionStats     `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	RecentActivities []*RecentActivity      `protobuf:"bytes,2,rep,name=recent_activities,json=recentActivities,proto3" json:"recent_activities,omitempty"`
	TopContributors  []*TopContributor      `protobuf:"bytes,3,rep,name=top_contributors,json=topContributors,proto3" json:"top_contributors,omitempty"`
	UrgentPending    []*PendingContribution `protobuf:"bytes,4,rep,name=urgent_pending,json=urgentPending,proto3" json:"urgent_pending,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DashboardOverview) Reset() {
	*x = DashboardOverview{}
	mi := &file_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardOverview) ProtoMessage() {}

func (x *DashboardOverview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardOverview.ProtoReflect.Descriptor instead.
func (*DashboardOverview) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *DashboardOverview) GetStats() *ContributionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *DashboardOverview) GetRecentActivities() []*RecentActivity {
	if x != nil {
		return x.RecentActivities
	}
	return nil
}

func (x *DashboardOverview) GetTopContributors() []*TopContributor {
	if x != nil {
		return x.TopContributors
	}
	return nil
}

func (x *DashboardOverview) GetUrgentPending() []*PendingContribution {
	if x != nil {
		return x.UrgentPending
	}
	return nil
}

// Recent activity
type RecentActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "contribution_created", "contribution_approved", "contribution_rejected"
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DigimonId     string                 `protobuf:"bytes,4,opt,name=digimon_id,json=digimonId,proto3" json:"digimon_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentActivity) Reset() {
	*x = RecentActivity{}
	mi := &file_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentActivity) ProtoMessage() {}

func (x *RecentActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentActivity.ProtoReflect.Descriptor instead.
func (*RecentActivity) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *RecentActivity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecentActivity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecentActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecentActivity) GetDigimonId() string {
	if x != nil {
		return x.DigimonId
	}
	return ""
}

func (x *RecentActivity) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RecentActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Top contributor
type TopContributor struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username              string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	TotalContributions    int32                  `protobuf:"varint,4,opt,name=total_contributions,json=totalContributions,proto3" json:"total_contributions,omitempty"`
	ApprovedContributions int32                  `protobuf:"varint,5,opt,name=approved_contributions,json=approvedContributions,proto3" json:"approved_contributions,omitempty"`
	ApprovalRate          float64                `protobuf:"fixed64,6,opt,name=approval_rate,json=approvalRate,proto3" json:"approval_rate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TopContributor) Reset() {
	*x = TopContributor{}
	mi := &file_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopContributor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopContributor) ProtoMessage() {}

func (x *TopContributor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopContributor.ProtoReflect.Descriptor instead.
func (*TopContributor) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *TopContributor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopContributor) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TopContributor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TopContributor) GetTotalContributions() int32 {
	if x != nil {
		return x.TotalContributions
	}
	return 0
}

func (x *TopContributor) GetApprovedContributions() int32 {
	if x != nil {
		return x.ApprovedContributions
	}
	return 0
}

func (x *TopContributor) GetApprovalRate() float64 {
	if x != nil {
		return x.ApprovalRate
	}
	return 0
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x05admin\"\xb1\x01\n" +
	"\x1eGetPendingContributionsRequest\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vfilter_type\x18\x03 \x01(\tR\n" +
	"filterType\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tR\tsortOrder\"\x84\x01\n" +
	"\x1fGetPendingContributionsResponse\x12@\n" +
	"\rcontributions\x18\x01 \x03(\v2\x1a.admin.PendingContributionR\rcontributions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa2\x02\n" +
	"\x1aApproveContributionRequest\x12'\n" +
	"\x0fcontribution_id\x18\x01 \x01(\tR\x0econtributionId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x1a\n" +
	"\bcomments\x18\x04 \x01(\tR\bcomments\x12K\n" +
	"\bmetadata\x18\x05 \x03(\v2/.admin.ApproveContributionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x1bApproveContributionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12L\n" +
	"\x14updated_contribution\x18\x03 \x01(\v2\x19.admin.ContributionStatusR\x13updatedContribution\"Y\n" +
	"\x1bGetContributionStatsRequest\x12\x1f\n" +
	"\vtime_period\x18\x01 \x01(\tR\n" +
	"timePeriod\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\"N\n" +
	"\x1cGetContributionStatsResponse\x12.\n" +
	"\x05stats\x18\x01 \x01(\v2\x18.admin.ContributionStatsR\x05stats\"8\n" +
	"\x1bGetDashboardOverviewRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\"T\n" +
	"\x1cGetDashboardOverviewResponse\x124\n" +
	"\boverview\x18\x01 \x01(\v2\x18.admin.DashboardOverviewR\boverview\"\xaf\x02\n" +
	"\x13PendingContribution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"digimon_id\x18\x03 \x01(\tR\tdigimonId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12,\n" +
	"\tuser_info\x18\b \x01(\v2\x0f.admin.UserInfoR\buserInfo\x125\n" +
	"\fdigimon_info\x18\t \x01(\v2\x12.admin.DigimonInfoR\vdigimonInfo\"\xef\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12/\n" +
	"\x13total_contributions\x18\x05 \x01(\x05R\x12totalContributions\x125\n" +
	"\x16approved_contributions\x18\x06 \x01(\x05R\x15approvedContributions\x12!\n" +
	"\fmember_since\x18\a \x01(\tR\vmemberSince\"q\n" +
	"\vDigimonInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"\x9a\x01\n" +
	"\x12ContributionStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vapproved_by\x18\x03 \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\x04 \x01(\tR\n" +
	"approvedAt\x12\x1a\n" +
	"\bcomments\x18\x05 \x01(\tR\bcomments\"\xfd\x02\n" +
	"\x11ContributionStats\x12#\n" +
	"\rtotal_pending\x18\x01 \x01(\x05R\ftotalPending\x12%\n" +
	"\x0etotal_approved\x18\x02 \x01(\x05R\rtotalApproved\x12%\n" +
	"\x0etotal_rejected\x18\x03 \x01(\x05R\rtotalRejected\x126\n" +
	"\x17new_contributions_today\x18\x04 \x01(\x05R\x15newContributionsToday\x12%\n" +
	"\x0eapproved_today\x18\x05 \x01(\x05R\rapprovedToday\x12%\n" +
	"\x0erejected_today\x18\x06 \x01(\x05R\rrejectedToday\x125\n" +
	"\aby_type\x18\a \x03(\v2\x1c.admin.ContributionTypeStatsR\x06byType\x128\n" +
	"\bby_stage\x18\b \x03(\v2\x1d.admin.ContributionStageStatsR\abyStage\"\x93\x01\n" +
	"\x15ContributionTypeStats\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x18\n" +
	"\apending\x18\x03 \x01(\x05R\apending\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\x05R\bapproved\x12\x1a\n" +
	"\brejected\x18\x05 \x01(\x05R\brejected\"\x96\x01\n" +
	"\x16ContributionStageStats\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x18\n" +
	"\apending\x18\x03 \x01(\x05R\apending\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\x05R\bapproved\x12\x1a\n" +
	"\brejected\x18\x05 \x01(\x05R\brejected\"\x8c\x02\n" +
	"\x11DashboardOverview\x12.\n" +
	"\x05stats\x18\x01 \x01(\v2\x18.admin.ContributionStatsR\x05stats\x12B\n" +
	"\x11recent_activities\x18\x02 \x03(\v2\x15.admin.RecentActivityR\x10recentActivities\x12@\n" +
	"\x10top_contributors\x18\x03 \x03(\v2\x15.admin.TopContributorR\x0ftopContributors\x12A\n" +
	"\x0eurgent_pending\x18\x04 \x03(\v2\x1a.admin.PendingContributionR\rurgentPending\"\xac\x01\n" +
	"\x0eRecentActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"digimon_id\x18\x04 \x01(\tR\tdigimonId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xe8\x01\n" +
	"\x0eTopContributor\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12/\n" +
	"\x13total_contributions\x18\x04 \x01(\x05R\x12totalContributions\x125\n" +
	"\x16approved_contributions\x18\x05 \x01(\x05R\x15approvedContributions\x12#\n" +
	"\rapproval_rate\x18\x06 \x01(\x01R\fapprovalRate2\x98\x03\n" +
	"\fAdminService\x12h\n" +
	"\x17GetPendingContributions\x12%.admin.GetPendingContributionsRequest\x1a&.admin.GetPendingContributionsResponse\x12\\\n" +
	"\x13ApproveContribution\x12!.admin.ApproveContributionRequest\x1a\".admin.ApproveContributionResponse\x12_\n" +
	"\x14GetContributionStats\x12\".admin.GetContributionStatsRequest\x1a#.admin.GetContributionStatsResponse\x12_\n" +
	"\x14GetDashboardOverview\x12\".admin.GetDashboardOverviewRequest\x1a#.admin.GetDashboardOverviewResponseB%Z#digimon-story-evolution/proto/adminb\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_admin_proto_goTypes = []any{
	(*GetPendingContributionsRequest)(nil),  // 0: admin.GetPendingContributionsRequest
	(*GetPendingContributionsResponse)(nil), // 1: admin.GetPendingContributionsResponse
	(*ApproveContributionRequest)(nil),      // 2: admin.ApproveContributionRequest
	(*ApproveContributionResponse)(nil),     // 3: admin.ApproveContributionResponse
	(*GetContributionStatsRequest)(nil),     // 4: admin.GetContributionStatsRequest
	(*GetContributionStatsResponse)(nil),    // 5: admin.GetContributionStatsResponse
	(*GetDashboardOverviewRequest)(nil),     // 6: admin.GetDashboardOverviewRequest
	(*GetDashboardOverviewResponse)(nil),    // 7: admin.GetDashboardOverviewResponse
	(*PendingContribution)(nil),             // 8: admin.PendingContribution
	(*UserInfo)(nil),                        // 9: admin.UserInfo
	(*DigimonInfo)(nil),                     // 10: admin.DigimonInfo
	(*ContributionStatus)(nil),              // 11: admin.ContributionStatus
	(*ContributionStats)(nil),               // 12: admin.ContributionStats
	(*ContributionTypeStats)(nil),           // 13: admin.ContributionTypeStats
	(*ContributionStageStats)(nil),          // 14: admin.ContributionStageStats
	(*DashboardOverview)(nil),               // 15: admin.DashboardOverview
	(*RecentActivity)(nil),                  // 16: admin.RecentActivity
	(*TopContributor)(nil),                  // 17: admin.TopContributor
	nil,                                     // 18: admin.ApproveContributionRequest.MetadataEntry
}
var file_proto_admin_proto_depIdxs = []int32{
	8,  // 0: admin.GetPendingContributionsResponse.contributions:type_name -> admin.PendingContribution
	18, // 1: admin.ApproveContributionRequest.metadata:type_name -> admin.ApproveContributionRequest.MetadataEntry
	11, // 2: admin.ApproveContributionResponse.updated_contribution:type_name -> admin.ContributionStatus
	12, // 3: admin.GetContributionStatsResponse.stats:type_name -> admin.ContributionStats
	15, // 4: admin.GetDashboardOverviewResponse.overview:type_name -> admin.DashboardOverview
	9,  // 5: admin.PendingContribution.user_info:type_name -> admin.UserInfo
	10, // 6: admin.PendingContribution.digimon_info:type_name -> admin.DigimonInfo
	13, // 7: admin.ContributionStats.by_type:type_name -> admin.ContributionTypeStats
	14, // 8: admin.ContributionStats.by_stage:type_name -> admin.ContributionStageStats
	12, // 9: admin.DashboardOverview.stats:type_name -> admin.ContributionStats
	16, // 10: admin.DashboardOverview.recent_activities:type_name -> admin.RecentActivity
	17, // 11: admin.DashboardOverview.top_contributors:type_name -> admin.TopContributor
	8,  // 12: admin.DashboardOverview.urgent_pending:type_name -> admin.PendingContribution
	0,  // 13: admin.AdminService.GetPendingContributions:input_type -> admin.GetPendingContributionsRequest
	2,  // 14: admin.AdminService.ApproveContribution:input_type -> admin.ApproveContributionRequest
	4,  // 15: admin.AdminService.GetContributionStats:input_type -> admin.GetContributionStatsRequest
	6,  // 16: admin.AdminService.GetDashboardOverview:input_type -> admin.GetDashboardOverviewRequest
	1,  // 17: admin.AdminService.GetPendingContributions:output_type -> admin.GetPendingContributionsResponse
	3,  // 18: admin.AdminService.ApproveContribution:output_type -> admin.ApproveContributionResponse
	5,  // 19: admin.AdminService.GetContributionStats:output_type -> admin.GetContributionStatsResponse
	7,  // 20: admin.AdminService.GetDashboardOverview:output_type -> admin.GetDashboardOverviewResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
