// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/digimon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for getting Digimon list
type GetDigimonListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int32                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Stage         []string               `protobuf:"bytes,5,rep,name=stage,proto3" json:"stage,omitempty"`
	Type          []string               `protobuf:"bytes,6,rep,name=type,proto3" json:"type,omitempty"`
	Attribute     []string               `protobuf:"bytes,7,rep,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigimonListRequest) Reset() {
	*x = GetDigimonListRequest{}
	mi := &file_proto_digimon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigimonListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigimonListRequest) ProtoMessage() {}

func (x *GetDigimonListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigimonListRequest.ProtoReflect.Descriptor instead.
func (*GetDigimonListRequest) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{0}
}

func (x *GetDigimonListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetDigimonListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetDigimonListRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetDigimonListRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *GetDigimonListRequest) GetStage() []string {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *GetDigimonListRequest) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *GetDigimonListRequest) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

// Response for Digimon list
type GetDigimonListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digimon       []*DigimonListItem     `protobuf:"bytes,1,rep,name=digimon,proto3" json:"digimon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigimonListResponse) Reset() {
	*x = GetDigimonListResponse{}
	mi := &file_proto_digimon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigimonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigimonListResponse) ProtoMessage() {}

func (x *GetDigimonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigimonListResponse.ProtoReflect.Descriptor instead.
func (*GetDigimonListResponse) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{1}
}

func (x *GetDigimonListResponse) GetDigimon() []*DigimonListItem {
	if x != nil {
		return x.Digimon
	}
	return nil
}

// Individual Digimon item in list
type DigimonListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Attribute     string                 `protobuf:"bytes,5,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigimonListItem) Reset() {
	*x = DigimonListItem{}
	mi := &file_proto_digimon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonListItem) ProtoMessage() {}

func (x *DigimonListItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonListItem.ProtoReflect.Descriptor instead.
func (*DigimonListItem) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{2}
}

func (x *DigimonListItem) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *DigimonListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DigimonListItem) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DigimonListItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DigimonListItem) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *DigimonListItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DigimonListItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

// Response for Digimon list size
type GetDigimonListSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigimonListSizeResponse) Reset() {
	*x = GetDigimonListSizeResponse{}
	mi := &file_proto_digimon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigimonListSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigimonListSizeResponse) ProtoMessage() {}

func (x *GetDigimonListSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigimonListSizeResponse.ProtoReflect.Descriptor instead.
func (*GetDigimonListSizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{3}
}

func (x *GetDigimonListSizeResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Request for getting Digimon details
type GetDigimonDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigimonDetailsRequest) Reset() {
	*x = GetDigimonDetailsRequest{}
	mi := &file_proto_digimon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigimonDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigimonDetailsRequest) ProtoMessage() {}

func (x *GetDigimonDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigimonDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetDigimonDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{4}
}

func (x *GetDigimonDetailsRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

// Response for Digimon details
type GetDigimonDetailsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Number           string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stage            string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Type             string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Attribute        string                 `protobuf:"bytes,5,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Image            string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Icon             string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Skills           []string               `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Attacks          []string               `protobuf:"bytes,10,rep,name=attacks,proto3" json:"attacks,omitempty"`
	SpecialAbilities []string               `protobuf:"bytes,11,rep,name=special_abilities,json=specialAbilities,proto3" json:"special_abilities,omitempty"`
	Stats            *DigimonStats          `protobuf:"bytes,12,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDigimonDetailsResponse) Reset() {
	*x = GetDigimonDetailsResponse{}
	mi := &file_proto_digimon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigimonDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigimonDetailsResponse) ProtoMessage() {}

func (x *GetDigimonDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigimonDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetDigimonDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{5}
}

func (x *GetDigimonDetailsResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetDigimonDetailsResponse) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetDigimonDetailsResponse) GetAttacks() []string {
	if x != nil {
		return x.Attacks
	}
	return nil
}

func (x *GetDigimonDetailsResponse) GetSpecialAbilities() []string {
	if x != nil {
		return x.SpecialAbilities
	}
	return nil
}

func (x *GetDigimonDetailsResponse) GetStats() *DigimonStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Digimon statistics
type DigimonStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hp            int32                  `protobuf:"varint,1,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            int32                  `protobuf:"varint,2,opt,name=mp,proto3" json:"mp,omitempty"`
	Attack        int32                  `protobuf:"varint,3,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int32                  `protobuf:"varint,4,opt,name=defense,proto3" json:"defense,omitempty"`
	Speed         int32                  `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Intelligence  int32                  `protobuf:"varint,6,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigimonStats) Reset() {
	*x = DigimonStats{}
	mi := &file_proto_digimon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonStats) ProtoMessage() {}

func (x *DigimonStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonStats.ProtoReflect.Descriptor instead.
func (*DigimonStats) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{6}
}

func (x *DigimonStats) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *DigimonStats) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *DigimonStats) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *DigimonStats) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *DigimonStats) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *DigimonStats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

// Response for Digimon evolutions
type GetDigimonEvolutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evolutions    []*DigimonEvolution    `protobuf:"bytes,1,rep,name=evolutions,proto3" json:"evolutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigimonEvolutionsResponse) Reset() {
	*x = GetDigimonEvolutionsResponse{}
	mi := &file_proto_digimon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigimonEvolutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigimonEvolutionsResponse) ProtoMessage() {}

func (x *GetDigimonEvolutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigimonEvolutionsResponse.ProtoReflect.Descriptor instead.
func (*GetDigimonEvolutionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{7}
}

func (x *GetDigimonEvolutionsResponse) GetEvolutions() []*DigimonEvolution {
	if x != nil {
		return x.Evolutions
	}
	return nil
}

// Individual evolution information
type DigimonEvolution struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Number        string                  `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stage         string                  `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Type          string                  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Attribute     string                  `protobuf:"bytes,5,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Image         string                  `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Icon          string                  `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Requirements  []*DigivolveRequirement `protobuf:"bytes,8,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigimonEvolution) Reset() {
	*x = DigimonEvolution{}
	mi := &file_proto_digimon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonEvolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonEvolution) ProtoMessage() {}

func (x *DigimonEvolution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonEvolution.ProtoReflect.Descriptor instead.
func (*DigimonEvolution) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{8}
}

func (x *DigimonEvolution) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *DigimonEvolution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DigimonEvolution) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DigimonEvolution) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DigimonEvolution) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *DigimonEvolution) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DigimonEvolution) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *DigimonEvolution) GetRequirements() []*DigivolveRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

// Digivolve requirements
type DigivolveRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigivolveRequirement) Reset() {
	*x = DigivolveRequirement{}
	mi := &file_proto_digimon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigivolveRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigivolveRequirement) ProtoMessage() {}

func (x *DigivolveRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_digimon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigivolveRequirement.ProtoReflect.Descriptor instead.
func (*DigivolveRequirement) Descriptor() ([]byte, []int) {
	return file_proto_digimon_proto_rawDescGZIP(), []int{9}
}

func (x *DigivolveRequirement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DigivolveRequirement) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DigivolveRequirement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_digimon_proto protoreflect.FileDescriptor

const file_proto_digimon_proto_rawDesc = "" +
	"\n" +
	"\x13proto/digimon.proto\x12\adigimon\"\xcf\x01\n" +
	"\x15GetDigimonListRequest\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\x12\x14\n" +
	"\x05stage\x18\x05 \x03(\tR\x05stage\x12\x12\n" +
	"\x04type\x18\x06 \x03(\tR\x04type\x12\x1c\n" +
	"\tattribute\x18\a \x03(\tR\tattribute\"L\n" +
	"\x16GetDigimonListResponse\x122\n" +
	"\adigimon\x18\x01 \x03(\v2\x18.digimon.DigimonListItemR\adigimon\"\xaf\x01\n" +
	"\x0fDigimonListItem\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\tattribute\x18\x05 \x01(\tR\tattribute\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\"0\n" +
	"\x1aGetDigimonListSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"2\n" +
	"\x18GetDigimonDetailsRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\"\xe7\x02\n" +
	"\x19GetDigimonDetailsResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\tattribute\x18\x05 \x01(\tR\tattribute\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x16\n" +
	"\x06skills\x18\t \x03(\tR\x06skills\x12\x18\n" +
	"\aattacks\x18\n" +
	" \x03(\tR\aattacks\x12+\n" +
	"\x11special_abilities\x18\v \x03(\tR\x10specialAbilities\x12+\n" +
	"\x05stats\x18\f \x01(\v2\x15.digimon.DigimonStatsR\x05stats\"\x9a\x01\n" +
	"\fDigimonStats\x12\x0e\n" +
	"\x02hp\x18\x01 \x01(\x05R\x02hp\x12\x0e\n" +
	"\x02mp\x18\x02 \x01(\x05R\x02mp\x12\x16\n" +
	"\x06attack\x18\x03 \x01(\x05R\x06attack\x12\x18\n" +
	"\adefense\x18\x04 \x01(\x05R\adefense\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x05R\x05speed\x12\"\n" +
	"\fintelligence\x18\x06 \x01(\x05R\fintelligence\"Y\n" +
	"\x1cGetDigimonEvolutionsResponse\x129\n" +
	"\n" +
	"evolutions\x18\x01 \x03(\v2\x19.digimon.DigimonEvolutionR\n" +
	"evolutions\"\xf3\x01\n" +
	"\x10DigimonEvolution\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\tattribute\x18\x05 \x01(\tR\tattribute\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12A\n" +
	"\frequirements\x18\b \x03(\v2\x1d.digimon.DigivolveRequirementR\frequirements\"b\n" +
	"\x14DigivolveRequirement\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\xfc\x02\n" +
	"\x0eDigimonService\x12Q\n" +
	"\x0eGetDigimonList\x12\x1e.digimon.GetDigimonListRequest\x1a\x1f.digimon.GetDigimonListResponse\x12Y\n" +
	"\x12GetDigimonListSize\x12\x1e.digimon.GetDigimonListRequest\x1a#.digimon.GetDigimonListSizeResponse\x12Z\n" +
	"\x11GetDigimonDetails\x12!.digimon.GetDigimonDetailsRequest\x1a\".digimon.GetDigimonDetailsResponse\x12`\n" +
	"\x14GetDigimonEvolutions\x12!.digimon.GetDigimonDetailsRequest\x1a%.digimon.GetDigimonEvolutionsResponseB\x1fZ\x1ddigimon-story-evolution/protob\x06proto3"

var (
	file_proto_digimon_proto_rawDescOnce sync.Once
	file_proto_digimon_proto_rawDescData []byte
)

func file_proto_digimon_proto_rawDescGZIP() []byte {
	file_proto_digimon_proto_rawDescOnce.Do(func() {
		file_proto_digimon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_digimon_proto_rawDesc), len(file_proto_digimon_proto_rawDesc)))
	})
	return file_proto_digimon_proto_rawDescData
}

var file_proto_digimon_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_digimon_proto_goTypes = []any{
	(*GetDigimonListRequest)(nil),        // 0: digimon.GetDigimonListRequest
	(*GetDigimonListResponse)(nil),       // 1: digimon.GetDigimonListResponse
	(*DigimonListItem)(nil),              // 2: digimon.DigimonListItem
	(*GetDigimonListSizeResponse)(nil),   // 3: digimon.GetDigimonListSizeResponse
	(*GetDigimonDetailsRequest)(nil),     // 4: digimon.GetDigimonDetailsRequest
	(*GetDigimonDetailsResponse)(nil),    // 5: digimon.GetDigimonDetailsResponse
	(*DigimonStats)(nil),                 // 6: digimon.DigimonStats
	(*GetDigimonEvolutionsResponse)(nil), // 7: digimon.GetDigimonEvolutionsResponse
	(*DigimonEvolution)(nil),             // 8: digimon.DigimonEvolution
	(*DigivolveRequirement)(nil),         // 9: digimon.DigivolveRequirement
}
var file_proto_digimon_proto_depIdxs = []int32{
	2, // 0: digimon.GetDigimonListResponse.digimon:type_name -> digimon.DigimonListItem
	6, // 1: digimon.GetDigimonDetailsResponse.stats:type_name -> digimon.DigimonStats
	8, // 2: digimon.GetDigimonEvolutionsResponse.evolutions:type_name -> digimon.DigimonEvolution
	9, // 3: digimon.DigimonEvolution.requirements:type_name -> digimon.DigivolveRequirement
	0, // 4: digimon.DigimonService.GetDigimonList:input_type -> digimon.GetDigimonListRequest
	0, // 5: digimon.DigimonService.GetDigimonListSize:input_type -> digimon.GetDigimonListRequest
	4, // 6: digimon.DigimonService.GetDigimonDetails:input_type -> digimon.GetDigimonDetailsRequest
	4, // 7: digimon.DigimonService.GetDigimonEvolutions:input_type -> digimon.GetDigimonDetailsRequest
	1, // 8: digimon.DigimonService.GetDigimonList:output_type -> digimon.GetDigimonListResponse
	3, // 9: digimon.DigimonService.GetDigimonListSize:output_type -> digimon.GetDigimonListSizeResponse
	5, // 10: digimon.DigimonService.GetDigimonDetails:output_type -> digimon.GetDigimonDetailsResponse
	7, // 11: digimon.DigimonService.GetDigimonEvolutions:output_type -> digimon.GetDigimonEvolutionsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_digimon_proto_init() }
func file_proto_digimon_proto_init() {
	if File_proto_digimon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_digimon_proto_rawDesc), len(file_proto_digimon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_digimon_proto_goTypes,
		DependencyIndexes: file_proto_digimon_proto_depIdxs,
		MessageInfos:      file_proto_digimon_proto_msgTypes,
	}.Build()
	File_proto_digimon_proto = out.File
	file_proto_digimon_proto_goTypes = nil
	file_proto_digimon_proto_depIdxs = nil
}
