// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/digimon.proto

package digimon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DigimonService_GetDigimonList_FullMethodName       = "/digimon.DigimonService/GetDigimonList"
	DigimonService_GetDigimonListSize_FullMethodName   = "/digimon.DigimonService/GetDigimonListSize"
	DigimonService_GetDigimonDetails_FullMethodName    = "/digimon.DigimonService/GetDigimonDetails"
	DigimonService_GetDigimonEvolutions_FullMethodName = "/digimon.DigimonService/GetDigimonEvolutions"
)

// DigimonServiceClient is the client API for DigimonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Digimon Service - handles all Digimon-related operations
type DigimonServiceClient interface {
	// Get list of Digimon with filtering and pagination
	GetDigimonList(ctx context.Context, in *GetDigimonListRequest, opts ...grpc.CallOption) (*GetDigimonListResponse, error)
	// Get total count of Digimon for pagination
	GetDigimonListSize(ctx context.Context, in *GetDigimonListRequest, opts ...grpc.CallOption) (*GetDigimonListSizeResponse, error)
	// Get detailed information about a specific Digimon
	GetDigimonDetails(ctx context.Context, in *GetDigimonDetailsRequest, opts ...grpc.CallOption) (*GetDigimonDetailsResponse, error)
	// Get evolution information for a Digimon
	GetDigimonEvolutions(ctx context.Context, in *GetDigimonDetailsRequest, opts ...grpc.CallOption) (*GetDigimonEvolutionsResponse, error)
}

type digimonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDigimonServiceClient(cc grpc.ClientConnInterface) DigimonServiceClient {
	return &digimonServiceClient{cc}
}

func (c *digimonServiceClient) GetDigimonList(ctx context.Context, in *GetDigimonListRequest, opts ...grpc.CallOption) (*GetDigimonListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDigimonListResponse)
	err := c.cc.Invoke(ctx, DigimonService_GetDigimonList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digimonServiceClient) GetDigimonListSize(ctx context.Context, in *GetDigimonListRequest, opts ...grpc.CallOption) (*GetDigimonListSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDigimonListSizeResponse)
	err := c.cc.Invoke(ctx, DigimonService_GetDigimonListSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digimonServiceClient) GetDigimonDetails(ctx context.Context, in *GetDigimonDetailsRequest, opts ...grpc.CallOption) (*GetDigimonDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDigimonDetailsResponse)
	err := c.cc.Invoke(ctx, DigimonService_GetDigimonDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digimonServiceClient) GetDigimonEvolutions(ctx context.Context, in *GetDigimonDetailsRequest, opts ...grpc.CallOption) (*GetDigimonEvolutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDigimonEvolutionsResponse)
	err := c.cc.Invoke(ctx, DigimonService_GetDigimonEvolutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DigimonServiceServer is the server API for DigimonService service.
// All implementations must embed UnimplementedDigimonServiceServer
// for forward compatibility.
//
// Digimon Service - handles all Digimon-related operations
type DigimonServiceServer interface {
	// Get list of Digimon with filtering and pagination
	GetDigimonList(context.Context, *GetDigimonListRequest) (*GetDigimonListResponse, error)
	// Get total count of Digimon for pagination
	GetDigimonListSize(context.Context, *GetDigimonListRequest) (*GetDigimonListSizeResponse, error)
	// Get detailed information about a specific Digimon
	GetDigimonDetails(context.Context, *GetDigimonDetailsRequest) (*GetDigimonDetailsResponse, error)
	// Get evolution information for a Digimon
	GetDigimonEvolutions(context.Context, *GetDigimonDetailsRequest) (*GetDigimonEvolutionsResponse, error)
	mustEmbedUnimplementedDigimonServiceServer()
}

// UnimplementedDigimonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDigimonServiceServer struct{}

func (UnimplementedDigimonServiceServer) GetDigimonList(context.Context, *GetDigimonListRequest) (*GetDigimonListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDigimonList not implemented")
}
func (UnimplementedDigimonServiceServer) GetDigimonListSize(context.Context, *GetDigimonListRequest) (*GetDigimonListSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDigimonListSize not implemented")
}
func (UnimplementedDigimonServiceServer) GetDigimonDetails(context.Context, *GetDigimonDetailsRequest) (*GetDigimonDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDigimonDetails not implemented")
}
func (UnimplementedDigimonServiceServer) GetDigimonEvolutions(context.Context, *GetDigimonDetailsRequest) (*GetDigimonEvolutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDigimonEvolutions not implemented")
}
func (UnimplementedDigimonServiceServer) mustEmbedUnimplementedDigimonServiceServer() {}
func (UnimplementedDigimonServiceServer) testEmbeddedByValue()                        {}

// UnsafeDigimonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DigimonServiceServer will
// result in compilation errors.
type UnsafeDigimonServiceServer interface {
	mustEmbedUnimplementedDigimonServiceServer()
}

func RegisterDigimonServiceServer(s grpc.ServiceRegistrar, srv DigimonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDigimonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DigimonService_ServiceDesc, srv)
}

func _DigimonService_GetDigimonList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDigimonListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigimonServiceServer).GetDigimonList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigimonService_GetDigimonList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigimonServiceServer).GetDigimonList(ctx, req.(*GetDigimonListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigimonService_GetDigimonListSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDigimonListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigimonServiceServer).GetDigimonListSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigimonService_GetDigimonListSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigimonServiceServer).GetDigimonListSize(ctx, req.(*GetDigimonListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigimonService_GetDigimonDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDigimonDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigimonServiceServer).GetDigimonDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigimonService_GetDigimonDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigimonServiceServer).GetDigimonDetails(ctx, req.(*GetDigimonDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigimonService_GetDigimonEvolutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDigimonDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigimonServiceServer).GetDigimonEvolutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigimonService_GetDigimonEvolutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigimonServiceServer).GetDigimonEvolutions(ctx, req.(*GetDigimonDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DigimonService_ServiceDesc is the grpc.ServiceDesc for DigimonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DigimonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digimon.DigimonService",
	HandlerType: (*DigimonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDigimonList",
			Handler:    _DigimonService_GetDigimonList_Handler,
		},
		{
			MethodName: "GetDigimonListSize",
			Handler:    _DigimonService_GetDigimonListSize_Handler,
		},
		{
			MethodName: "GetDigimonDetails",
			Handler:    _DigimonService_GetDigimonDetails_Handler,
		},
		{
			MethodName: "GetDigimonEvolutions",
			Handler:    _DigimonService_GetDigimonEvolutions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/digimon.proto",
}
