// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for creating a contribution
type CreateContributionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DigimonId     string                 `protobuf:"bytes,2,opt,name=digimon_id,json=digimonId,proto3" json:"digimon_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "new", "update", "correction"
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContributionRequest) Reset() {
	*x = CreateContributionRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContributionRequest) ProtoMessage() {}

func (x *CreateContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContributionRequest.ProtoReflect.Descriptor instead.
func (*CreateContributionRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContributionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateContributionRequest) GetDigimonId() string {
	if x != nil {
		return x.DigimonId
	}
	return ""
}

func (x *CreateContributionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateContributionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateContributionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response for creating a contribution
type CreateContributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contribution  *Contribution          `protobuf:"bytes,1,opt,name=contribution,proto3" json:"contribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContributionResponse) Reset() {
	*x = CreateContributionResponse{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContributionResponse) ProtoMessage() {}

func (x *CreateContributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContributionResponse.ProtoReflect.Descriptor instead.
func (*CreateContributionResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContributionResponse) GetContribution() *Contribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

// Request for getting user contributions
type GetUserContributionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "pending", "approved", "rejected"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContributionsRequest) Reset() {
	*x = GetUserContributionsRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContributionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContributionsRequest) ProtoMessage() {}

func (x *GetUserContributionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContributionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserContributionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserContributionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserContributionsRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetUserContributionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserContributionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Response for user contributions
type GetUserContributionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contributions []*Contribution        `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContributionsResponse) Reset() {
	*x = GetUserContributionsResponse{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContributionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContributionsResponse) ProtoMessage() {}

func (x *GetUserContributionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContributionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserContributionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserContributionsResponse) GetContributions() []*Contribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

func (x *GetUserContributionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request for getting a specific contribution
type GetContributionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContributionId string                 `protobuf:"bytes,1,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetContributionRequest) Reset() {
	*x = GetContributionRequest{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContributionRequest) ProtoMessage() {}

func (x *GetContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContributionRequest.ProtoReflect.Descriptor instead.
func (*GetContributionRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetContributionRequest) GetContributionId() string {
	if x != nil {
		return x.ContributionId
	}
	return ""
}

// Response for getting a contribution
type GetContributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contribution  *Contribution          `protobuf:"bytes,1,opt,name=contribution,proto3" json:"contribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContributionResponse) Reset() {
	*x = GetContributionResponse{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContributionResponse) ProtoMessage() {}

func (x *GetContributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContributionResponse.ProtoReflect.Descriptor instead.
func (*GetContributionResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetContributionResponse) GetContribution() *Contribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

// Request for updating a contribution
type UpdateContributionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContributionId string                 `protobuf:"bytes,1,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateContributionRequest) Reset() {
	*x = UpdateContributionRequest{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContributionRequest) ProtoMessage() {}

func (x *UpdateContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContributionRequest.ProtoReflect.Descriptor instead.
func (*UpdateContributionRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateContributionRequest) GetContributionId() string {
	if x != nil {
		return x.ContributionId
	}
	return ""
}

func (x *UpdateContributionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateContributionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response for updating a contribution
type UpdateContributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contribution  *Contribution          `protobuf:"bytes,1,opt,name=contribution,proto3" json:"contribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContributionResponse) Reset() {
	*x = UpdateContributionResponse{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContributionResponse) ProtoMessage() {}

func (x *UpdateContributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContributionResponse.ProtoReflect.Descriptor instead.
func (*UpdateContributionResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContributionResponse) GetContribution() *Contribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

// Request for deleting a contribution
type DeleteContributionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContributionId string                 `protobuf:"bytes,1,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteContributionRequest) Reset() {
	*x = DeleteContributionRequest{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContributionRequest) ProtoMessage() {}

func (x *DeleteContributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContributionRequest.ProtoReflect.Descriptor instead.
func (*DeleteContributionRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteContributionRequest) GetContributionId() string {
	if x != nil {
		return x.ContributionId
	}
	return ""
}

func (x *DeleteContributionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response for deleting a contribution
type DeleteContributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContributionResponse) Reset() {
	*x = DeleteContributionResponse{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContributionResponse) ProtoMessage() {}

func (x *DeleteContributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContributionResponse.ProtoReflect.Descriptor instead.
func (*DeleteContributionResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteContributionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Contribution message
type Contribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DigimonId     string                 `protobuf:"bytes,3,opt,name=digimon_id,json=digimonId,proto3" json:"digimon_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "pending", "approved", "rejected"
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserInfo      *UserInfo              `protobuf:"bytes,10,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contribution) Reset() {
	*x = Contribution{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contribution) ProtoMessage() {}

func (x *Contribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contribution.ProtoReflect.Descriptor instead.
func (*Contribution) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *Contribution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contribution) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Contribution) GetDigimonId() string {
	if x != nil {
		return x.DigimonId
	}
	return ""
}

func (x *Contribution) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Contribution) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Contribution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Contribution) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Contribution) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Contribution) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Contribution) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// User information
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\"\x91\x02\n" +
	"\x19CreateContributionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"digimon_id\x18\x02 \x01(\tR\tdigimonId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.user.CreateContributionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x1aCreateContributionResponse\x126\n" +
	"\fcontribution\x18\x01 \x01(\v2\x12.user.ContributionR\fcontribution\"\x86\x01\n" +
	"\x1bGetUserContributionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"y\n" +
	"\x1cGetUserContributionsResponse\x128\n" +
	"\rcontributions\x18\x01 \x03(\v2\x12.user.ContributionR\rcontributions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"A\n" +
	"\x16GetContributionRequest\x12'\n" +
	"\x0fcontribution_id\x18\x01 \x01(\tR\x0econtributionId\"Q\n" +
	"\x17GetContributionResponse\x126\n" +
	"\fcontribution\x18\x01 \x01(\v2\x12.user.ContributionR\fcontribution\"\xee\x01\n" +
	"\x19UpdateContributionRequest\x12'\n" +
	"\x0fcontribution_id\x18\x01 \x01(\tR\x0econtributionId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.user.UpdateContributionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x1aUpdateContributionResponse\x126\n" +
	"\fcontribution\x18\x01 \x01(\v2\x12.user.ContributionR\fcontribution\"]\n" +
	"\x19DeleteContributionRequest\x12'\n" +
	"\x0fcontribution_id\x18\x01 \x01(\tR\x0econtributionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x1aDeleteContributionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8a\x03\n" +
	"\fContribution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"digimon_id\x18\x03 \x01(\tR\tdigimonId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12<\n" +
	"\bmetadata\x18\t \x03(\v2 .user.Contribution.MetadataEntryR\bmetadata\x12+\n" +
	"\tuser_info\x18\n" +
	" \x01(\v2\x0e.user.UserInfoR\buserInfo\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar2\xc7\x03\n" +
	"\vUserService\x12W\n" +
	"\x12CreateContribution\x12\x1f.user.CreateContributionRequest\x1a .user.CreateContributionResponse\x12]\n" +
	"\x14GetUserContributions\x12!.user.GetUserContributionsRequest\x1a\".user.GetUserContributionsResponse\x12N\n" +
	"\x0fGetContribution\x12\x1c.user.GetContributionRequest\x1a\x1d.user.GetContributionResponse\x12W\n" +
	"\x12UpdateContribution\x12\x1f.user.UpdateContributionRequest\x1a .user.UpdateContributionResponse\x12W\n" +
	"\x12DeleteContribution\x12\x1f.user.DeleteContributionRequest\x1a .user.DeleteContributionResponseB$Z\"digimon-story-evolution/proto/userb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_user_proto_goTypes = []any{
	(*CreateContributionRequest)(nil),    // 0: user.CreateContributionRequest
	(*CreateContributionResponse)(nil),   // 1: user.CreateContributionResponse
	(*GetUserContributionsRequest)(nil),  // 2: user.GetUserContributionsRequest
	(*GetUserContributionsResponse)(nil), // 3: user.GetUserContributionsResponse
	(*GetContributionRequest)(nil),       // 4: user.GetContributionRequest
	(*GetContributionResponse)(nil),      // 5: user.GetContributionResponse
	(*UpdateContributionRequest)(nil),    // 6: user.UpdateContributionRequest
	(*UpdateContributionResponse)(nil),   // 7: user.UpdateContributionResponse
	(*DeleteContributionRequest)(nil),    // 8: user.DeleteContributionRequest
	(*DeleteContributionResponse)(nil),   // 9: user.DeleteContributionResponse
	(*Contribution)(nil),                 // 10: user.Contribution
	(*UserInfo)(nil),                     // 11: user.UserInfo
	nil,                                  // 12: user.CreateContributionRequest.MetadataEntry
	nil,                                  // 13: user.UpdateContributionRequest.MetadataEntry
	nil,                                  // 14: user.Contribution.MetadataEntry
}
var file_proto_user_proto_depIdxs = []int32{
	12, // 0: user.CreateContributionRequest.metadata:type_name -> user.CreateContributionRequest.MetadataEntry
	10, // 1: user.CreateContributionResponse.contribution:type_name -> user.Contribution
	10, // 2: user.GetUserContributionsResponse.contributions:type_name -> user.Contribution
	10, // 3: user.GetContributionResponse.contribution:type_name -> user.Contribution
	13, // 4: user.UpdateContributionRequest.metadata:type_name -> user.UpdateContributionRequest.MetadataEntry
	10, // 5: user.UpdateContributionResponse.contribution:type_name -> user.Contribution
	14, // 6: user.Contribution.metadata:type_name -> user.Contribution.MetadataEntry
	11, // 7: user.Contribution.user_info:type_name -> user.UserInfo
	0,  // 8: user.UserService.CreateContribution:input_type -> user.CreateContributionRequest
	2,  // 9: user.UserService.GetUserContributions:input_type -> user.GetUserContributionsRequest
	4,  // 10: user.UserService.GetContribution:input_type -> user.GetContributionRequest
	6,  // 11: user.UserService.UpdateContribution:input_type -> user.UpdateContributionRequest
	8,  // 12: user.UserService.DeleteContribution:input_type -> user.DeleteContributionRequest
	1,  // 13: user.UserService.CreateContribution:output_type -> user.CreateContributionResponse
	3,  // 14: user.UserService.GetUserContributions:output_type -> user.GetUserContributionsResponse
	5,  // 15: user.UserService.GetContribution:output_type -> user.GetContributionResponse
	7,  // 16: user.UserService.UpdateContribution:output_type -> user.UpdateContributionResponse
	9,  // 17: user.UserService.DeleteContribution:output_type -> user.DeleteContributionResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
