// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CreateContribution_FullMethodName   = "/user.UserService/CreateContribution"
	UserService_GetUserContributions_FullMethodName = "/user.UserService/GetUserContributions"
	UserService_GetContribution_FullMethodName      = "/user.UserService/GetContribution"
	UserService_UpdateContribution_FullMethodName   = "/user.UserService/UpdateContribution"
	UserService_DeleteContribution_FullMethodName   = "/user.UserService/DeleteContribution"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// User Service - handles user management and contributions
type UserServiceClient interface {
	// Create a new user contribution
	CreateContribution(ctx context.Context, in *CreateContributionRequest, opts ...grpc.CallOption) (*CreateContributionResponse, error)
	// Get user's contributions
	GetUserContributions(ctx context.Context, in *GetUserContributionsRequest, opts ...grpc.CallOption) (*GetUserContributionsResponse, error)
	// Get a specific contribution
	GetContribution(ctx context.Context, in *GetContributionRequest, opts ...grpc.CallOption) (*GetContributionResponse, error)
	// Update a contribution
	UpdateContribution(ctx context.Context, in *UpdateContributionRequest, opts ...grpc.CallOption) (*UpdateContributionResponse, error)
	// Delete a contribution
	DeleteContribution(ctx context.Context, in *DeleteContributionRequest, opts ...grpc.CallOption) (*DeleteContributionResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateContribution(ctx context.Context, in *CreateContributionRequest, opts ...grpc.CallOption) (*CreateContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContributionResponse)
	err := c.cc.Invoke(ctx, UserService_CreateContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserContributions(ctx context.Context, in *GetUserContributionsRequest, opts ...grpc.CallOption) (*GetUserContributionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserContributionsResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserContributions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetContribution(ctx context.Context, in *GetContributionRequest, opts ...grpc.CallOption) (*GetContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContributionResponse)
	err := c.cc.Invoke(ctx, UserService_GetContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateContribution(ctx context.Context, in *UpdateContributionRequest, opts ...grpc.CallOption) (*UpdateContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContributionResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteContribution(ctx context.Context, in *DeleteContributionRequest, opts ...grpc.CallOption) (*DeleteContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContributionResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// User Service - handles user management and contributions
type UserServiceServer interface {
	// Create a new user contribution
	CreateContribution(context.Context, *CreateContributionRequest) (*CreateContributionResponse, error)
	// Get user's contributions
	GetUserContributions(context.Context, *GetUserContributionsRequest) (*GetUserContributionsResponse, error)
	// Get a specific contribution
	GetContribution(context.Context, *GetContributionRequest) (*GetContributionResponse, error)
	// Update a contribution
	UpdateContribution(context.Context, *UpdateContributionRequest) (*UpdateContributionResponse, error)
	// Delete a contribution
	DeleteContribution(context.Context, *DeleteContributionRequest) (*DeleteContributionResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateContribution(context.Context, *CreateContributionRequest) (*CreateContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContribution not implemented")
}
func (UnimplementedUserServiceServer) GetUserContributions(context.Context, *GetUserContributionsRequest) (*GetUserContributionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserContributions not implemented")
}
func (UnimplementedUserServiceServer) GetContribution(context.Context, *GetContributionRequest) (*GetContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContribution not implemented")
}
func (UnimplementedUserServiceServer) UpdateContribution(context.Context, *UpdateContributionRequest) (*UpdateContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContribution not implemented")
}
func (UnimplementedUserServiceServer) DeleteContribution(context.Context, *DeleteContributionRequest) (*DeleteContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContribution not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateContribution(ctx, req.(*CreateContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserContributions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserContributionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserContributions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserContributions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserContributions(ctx, req.(*GetUserContributionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetContribution(ctx, req.(*GetContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateContribution(ctx, req.(*UpdateContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteContribution(ctx, req.(*DeleteContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContribution",
			Handler:    _UserService_CreateContribution_Handler,
		},
		{
			MethodName: "GetUserContributions",
			Handler:    _UserService_GetUserContributions_Handler,
		},
		{
			MethodName: "GetContribution",
			Handler:    _UserService_GetContribution_Handler,
		},
		{
			MethodName: "UpdateContribution",
			Handler:    _UserService_UpdateContribution_Handler,
		},
		{
			MethodName: "DeleteContribution",
			Handler:    _UserService_DeleteContribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
